/**
 * nx00_view.code（與 seed 一致）— API 權限檢查用。
 */
export const NX00_VIEW = {
    USER: 'NX00_USER',
    ROLE: 'NX00_ROLE',
    USER_ROLE: 'NX00_USER_ROLE',
    USER_WAREHOUSE: 'NX00_USER_WAREHOUSE',
    ROLE_VIEW: 'NX00_ROLE_VIEW',
    PART: 'NX00_PART',
    BRAND: 'NX00_BRAND',
    CAR_BRAND: 'NX00_CAR_BRAND',
    PART_BRAND: 'NX00_PART_BRAND',
    WAREHOUSE: 'NX00_WAREHOUSE',
    LOCATION: 'NX00_LOCATION',
    PARTNER: 'NX00_PARTNER',

    /** NX02 庫存作業（第二批） */
    NX02_INIT: 'NX02_INIT',
    NX02_STOCK_SETTING: 'NX02_STOCK_SETTING',
    NX02_STOCK_TAKE: 'NX02_STOCK_TAKE',

    /** NX01 採購 */
    NX01_HOME: 'NX01_HOME',
    NX01_RFQ: 'NX01_RFQ',
    NX01_PO: 'NX01_PO',
    NX01_RR: 'NX01_RR',
    NX01_PR: 'NX01_PR',
} as const;
