-- =========================================================
-- Migration: NX00-DB-003
-- Purpose:
--   - Create NX00 core tables (remaining):
--     nx00_permission, nx00_role_permission,
--     nx00_warehouse, nx00_location,
--     nx00_business_partner, nx00_audit_log
--   - ID rule: VARCHAR(15) generated by DB (function + sequence)
-- Notes:
--   - Reuse trg_set_updated_at() if already exists (from NX00-DB-002)
--   - All created_at default now()
--   - is_active default true
-- =========================================================

-- -----------------------------
-- 0) Sequences
-- -----------------------------
CREATE SEQUENCE IF NOT EXISTS seq_nx00_perm START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_rope START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_ware START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_loca START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_bupa START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_aulo START 1;

-- -----------------------------
-- 1) ID generator functions
-- -----------------------------
CREATE OR REPLACE FUNCTION gen_nx00_permission_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[PERM]+[7碼流水號] => NX00PERM0000001
  RETURN 'NX00PERM' || LPAD(nextval('seq_nx00_perm')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_role_permission_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[ROPE]+[7碼流水號] => NX00ROPE0000001
  RETURN 'NX00ROPE' || LPAD(nextval('seq_nx00_rope')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_warehouse_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[WARE]+[7碼流水號] => NX00WARE0000001
  RETURN 'NX00WARE' || LPAD(nextval('seq_nx00_ware')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_location_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[LOCA]+[7碼流水號] => NX00LOCA0000001
  RETURN 'NX00LOCA' || LPAD(nextval('seq_nx00_loca')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_business_partner_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[BUPA]+[7碼流水號] => NX00BUPA0000001
  RETURN 'NX00BUPA' || LPAD(nextval('seq_nx00_bupa')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_audit_log_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[AULO]+[7碼流水號] => NX00AULO0000001
  RETURN 'NX00AULO' || LPAD(nextval('seq_nx00_aulo')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

-- -----------------------------
-- 2) updated_at trigger function (safe)
-- -----------------------------
-- 若上一支 migration 已建立 trg_set_updated_at()，這裡 OR REPLACE 不會破壞現況
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 3) Tables
-- Order: referenced tables first
-- =========================================================

-- -----------------------------
-- 3.1) nx00_permission
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_permission (
  id          VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_permission_id(),
  code        VARCHAR(80) NOT NULL UNIQUE,
  name        VARCHAR(80) NOT NULL,
  module_code VARCHAR(10) NOT NULL,
  action      VARCHAR(20) NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_no     INT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  created_by  VARCHAR(15) REFERENCES nx00_user(id),
  updated_at  TIMESTAMP,
  updated_by  VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_permission_set_updated_at
BEFORE UPDATE ON nx00_permission
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_nx00_permission_is_active ON nx00_permission(is_active);
CREATE INDEX IF NOT EXISTS idx_nx00_permission_module_code ON nx00_permission(module_code);

-- -----------------------------
-- 3.2) nx00_role_permission
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_role_permission (
  id             VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_role_permission_id(),
  role_id        VARCHAR(15) NOT NULL REFERENCES nx00_role(id) ON DELETE RESTRICT,
  permission_id  VARCHAR(15) NOT NULL REFERENCES nx00_permission(id) ON DELETE RESTRICT,
  created_at     TIMESTAMP NOT NULL DEFAULT now(),
  created_by     VARCHAR(15) REFERENCES nx00_user(id)
);

-- 避免同一角色重複綁同一權限
CREATE UNIQUE INDEX IF NOT EXISTS uq_nx00_role_permission_role_perm
ON nx00_role_permission(role_id, permission_id);

CREATE INDEX IF NOT EXISTS idx_nx00_role_permission_role_id ON nx00_role_permission(role_id);
CREATE INDEX IF NOT EXISTS idx_nx00_role_permission_permission_id ON nx00_role_permission(permission_id);

-- -----------------------------
-- 3.3) nx00_warehouse
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_warehouse (
  id          VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_warehouse_id(),
  code        VARCHAR(10) NOT NULL UNIQUE,
  name        VARCHAR(50) NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  remark      VARCHAR(255),
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  created_by  VARCHAR(15) REFERENCES nx00_user(id),
  updated_at  TIMESTAMP,
  updated_by  VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_warehouse_set_updated_at
BEFORE UPDATE ON nx00_warehouse
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_nx00_warehouse_is_active ON nx00_warehouse(is_active);

-- -----------------------------
-- 3.4) nx00_location
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_location (
  id            VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_location_id(),
  warehouse_id  VARCHAR(15) NOT NULL REFERENCES nx00_warehouse(id) ON DELETE RESTRICT,
  code          VARCHAR(10) NOT NULL UNIQUE,
  name          VARCHAR(50),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  remark        VARCHAR(255),
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  created_by    VARCHAR(15) REFERENCES nx00_user(id),
  updated_at    TIMESTAMP,
  updated_by    VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_location_set_updated_at
BEFORE UPDATE ON nx00_location
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_nx00_location_warehouse_id ON nx00_location(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_nx00_location_is_active ON nx00_location(is_active);

-- -----------------------------
-- 3.5) nx00_business_partner
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_business_partner (
  id           VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_business_partner_id(),
  code         VARCHAR(10) NOT NULL UNIQUE,
  name         VARCHAR(50) NOT NULL,
  tax_id       VARCHAR(20),
  phone        VARCHAR(30),
  email        VARCHAR(100),
  address      VARCHAR(255),
  is_customer  BOOLEAN NOT NULL DEFAULT FALSE,
  is_vendor    BOOLEAN NOT NULL DEFAULT FALSE,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  remark       VARCHAR(255),
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  created_by   VARCHAR(15) REFERENCES nx00_user(id),
  updated_at   TIMESTAMP,
  updated_by   VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_business_partner_set_updated_at
BEFORE UPDATE ON nx00_business_partner
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_nx00_business_partner_is_active ON nx00_business_partner(is_active);
CREATE INDEX IF NOT EXISTS idx_nx00_business_partner_is_customer ON nx00_business_partner(is_customer);
CREATE INDEX IF NOT EXISTS idx_nx00_business_partner_is_vendor ON nx00_business_partner(is_vendor);

-- -----------------------------
-- 3.6) nx00_audit_log
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_audit_log (
  id          VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_audit_log_id(),
  user_id     VARCHAR(15) NOT NULL REFERENCES nx00_user(id) ON DELETE RESTRICT,
  module_code VARCHAR(10) NOT NULL,
  action      VARCHAR(20) NOT NULL,
  entity      VARCHAR(50) NOT NULL,
  entity_id   VARCHAR(15),
  doc_no      VARCHAR(50),
  ip_address  VARCHAR(45),
  user_agent  VARCHAR(255),
  payload     JSON,
  created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nx00_audit_log_user_id ON nx00_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_nx00_audit_log_module_code ON nx00_audit_log(module_code);
CREATE INDEX IF NOT EXISTS idx_nx00_audit_log_entity ON nx00_audit_log(entity);
CREATE INDEX IF NOT EXISTS idx_nx00_audit_log_created_at ON nx00_audit_log(created_at);