-- =========================================================
-- Migration: NX00-DB-002
-- Purpose:
--   - Create NX00 master data tables:
--     nx00_brand, nx00_function_group, nx00_part_status, nx00_part
--   - ID rule: VARCHAR(15) generated by DB (function + sequence)
-- Notes:
--   - Prisma schema: no @default() on id, DB generates it
--   - created_at default now()
--   - is_active default true
--   - updated_at set automatically on UPDATE via trigger
-- =========================================================

-- -----------------------------
-- 0) Sequences
-- -----------------------------
CREATE SEQUENCE IF NOT EXISTS seq_nx00_bran START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_fugr START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_past START 1;
CREATE SEQUENCE IF NOT EXISTS seq_nx00_part START 1;

-- -----------------------------
-- 1) ID generator functions
-- -----------------------------
CREATE OR REPLACE FUNCTION gen_nx00_brand_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[BRAN]+[7碼流水號] => NX00BRAN0000001
  RETURN 'NX00BRAN' || LPAD(nextval('seq_nx00_bran')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_function_group_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[FUGR]+[7碼流水號] => NX00FUGR0000001
  RETURN 'NX00FUGR' || LPAD(nextval('seq_nx00_fugr')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_part_status_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[PAST]+[7碼流水號] => NX00PAST0000001
  RETURN 'NX00PAST' || LPAD(nextval('seq_nx00_past')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gen_nx00_part_id()
RETURNS varchar AS $$
BEGIN
  -- [NX00]+[PART]+[7碼流水號] => NX00PART0000001
  RETURN 'NX00PART' || LPAD(nextval('seq_nx00_part')::text, 7, '0');
END;
$$ LANGUAGE plpgsql;

-- -----------------------------
-- 2) updated_at trigger function
-- -----------------------------
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 3) Tables
-- Order: referenced tables first
-- =========================================================

-- -----------------------------
-- 3.1) nx00_brand
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_brand (
  -- 1 id (PK/UQ/NN, gen)
  id          VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_brand_id(),

  -- 2 code (UQ/NN)
  code        VARCHAR(30) NOT NULL UNIQUE,

  -- 3 name (NN)
  name        VARCHAR(50) NOT NULL,

  -- 4 name_en (nullable)
  name_en     VARCHAR(50),

  -- 5 is_active (NN default TRUE)
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,

  -- 6 remark (nullable)
  remark      VARCHAR(255),

  -- 7 created_at (NN default now)
  created_at  TIMESTAMP NOT NULL DEFAULT now(),

  -- 8 created_by (FK -> nx00_user.id, nullable)
  created_by  VARCHAR(15) REFERENCES nx00_user(id),

  -- 9 updated_at (nullable)
  updated_at  TIMESTAMP,

  -- 10 updated_by (FK -> nx00_user.id, nullable)
  updated_by  VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_brand_set_updated_at
BEFORE UPDATE ON nx00_brand
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

-- -----------------------------
-- 3.2) nx00_function_group
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_function_group (
  -- 1 id (PK/UQ/NN, gen)
  id          VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_function_group_id(),

  -- 2 code (UQ/NN)
  code        VARCHAR(30) NOT NULL UNIQUE,

  -- 3 name (NN)
  name        VARCHAR(50) NOT NULL,

  -- 4 description (nullable)
  description VARCHAR(255),

  -- 5 is_active (NN default TRUE)
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,

  -- 6 sort_no (nullable)
  sort_no     INT,

  -- 7 created_at (NN default now)
  created_at  TIMESTAMP NOT NULL DEFAULT now(),

  -- 8 created_by (FK -> nx00_user.id, nullable)
  created_by  VARCHAR(15) REFERENCES nx00_user(id),

  -- 9 updated_at (nullable)
  updated_at  TIMESTAMP,

  -- 10 updated_by (FK -> nx00_user.id, nullable)
  updated_by  VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_function_group_set_updated_at
BEFORE UPDATE ON nx00_function_group
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

-- -----------------------------
-- 3.3) nx00_part_status
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_part_status (
  -- 1 id (PK/UQ/NN, gen)
  id            VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_part_status_id(),

  -- 2 code (UQ/NN)
  code          VARCHAR(10) NOT NULL UNIQUE,

  -- 3 name (NN)
  name          VARCHAR(50) NOT NULL,

  -- 4 can_sell (NN default TRUE)
  can_sell      BOOLEAN NOT NULL DEFAULT TRUE,

  -- 5 can_purchase (NN default TRUE)
  can_purchase  BOOLEAN NOT NULL DEFAULT TRUE,

  -- 6 is_active (NN default TRUE)
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,

  -- 7 remark (nullable)
  remark        VARCHAR(255),

  -- 8 created_at (NN default now)
  created_at    TIMESTAMP NOT NULL DEFAULT now(),

  -- 9 created_by (FK -> nx00_user.id, nullable)
  created_by    VARCHAR(15) REFERENCES nx00_user(id),

  -- 10 updated_at (nullable)
  updated_at    TIMESTAMP,

  -- 11 updated_by (FK -> nx00_user.id, nullable)
  updated_by    VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_part_status_set_updated_at
BEFORE UPDATE ON nx00_part_status
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

-- -----------------------------
-- 3.4) nx00_part
-- -----------------------------
CREATE TABLE IF NOT EXISTS nx00_part (
  -- 1 id (PK/UQ/NN, gen)
  id                VARCHAR(15) PRIMARY KEY DEFAULT gen_nx00_part_id(),

  -- 2 part_no (UQ/NN)
  part_no           VARCHAR(50) NOT NULL UNIQUE,

  -- 3 old_part_no (nullable)
  old_part_no       VARCHAR(50),

  -- 4 display_no (nullable)
  display_no        VARCHAR(50),

  -- 5 name_zh (NN)
  name_zh           VARCHAR(100) NOT NULL,

  -- 6 name_en (nullable)
  name_en           VARCHAR(100),

  -- 7 brand_id (NN FK -> nx00_brand.id)
  brand_id          VARCHAR(15) NOT NULL REFERENCES nx00_brand(id),

  -- 8 function_group_id (nullable FK -> nx00_function_group.id)
  function_group_id VARCHAR(15) REFERENCES nx00_function_group(id),

  -- 9 status_id (NN FK -> nx00_part_status.id)
  status_id         VARCHAR(15) NOT NULL REFERENCES nx00_part_status(id),

  -- 10 barcode (nullable)
  barcode           VARCHAR(100),

  -- 11 is_active (NN default TRUE)
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,

  -- 12 remark (nullable)
  remark            VARCHAR(255),

  -- 13 created_at (NN default now)
  created_at        TIMESTAMP NOT NULL DEFAULT now(),

  -- 14 created_by (FK -> nx00_user.id, nullable)
  created_by        VARCHAR(15) REFERENCES nx00_user(id),

  -- 15 updated_at (nullable)
  updated_at        TIMESTAMP,

  -- 16 updated_by (FK -> nx00_user.id, nullable)
  updated_by        VARCHAR(15) REFERENCES nx00_user(id)
);

CREATE TRIGGER trg_nx00_part_set_updated_at
BEFORE UPDATE ON nx00_part
FOR EACH ROW
EXECUTE FUNCTION trg_set_updated_at();

-- =========================================================
-- 4) Indexes (for API query performance)
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_nx00_part_brand_id ON nx00_part(brand_id);
CREATE INDEX IF NOT EXISTS idx_nx00_part_function_group_id ON nx00_part(function_group_id);
CREATE INDEX IF NOT EXISTS idx_nx00_part_status_id ON nx00_part(status_id);
CREATE INDEX IF NOT EXISTS idx_nx00_part_is_active ON nx00_part(is_active);

CREATE INDEX IF NOT EXISTS idx_nx00_brand_is_active ON nx00_brand(is_active);
CREATE INDEX IF NOT EXISTS idx_nx00_function_group_is_active ON nx00_function_group(is_active);
CREATE INDEX IF NOT EXISTS idx_nx00_part_status_is_active ON nx00_part_status(is_active);

-- =========================================================
-- 5) Seeds (minimal to make UI/API runnable)
-- =========================================================

-- 5.1) nx00_part_status (N/Z/X)
INSERT INTO nx00_part_status (code, name, can_sell, can_purchase, is_active)
VALUES
('N', '正常件', TRUE, TRUE, TRUE),
('Z', '瑕疵件', TRUE, TRUE, TRUE),
('X', '中古件', TRUE, TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- 5.2) nx00_function_group (basic groups)
INSERT INTO nx00_function_group (code, name, description, is_active, sort_no)
VALUES
('ENGINE',   '引擎系統',   NULL, TRUE, 10),
('ELECTRIC', '電系/電裝',  NULL, TRUE, 20),
('BRAKE',    '煞車系統',   NULL, TRUE, 30),
('SUSP',     '底盤懸吊',   NULL, TRUE, 40),
('MAINT',    '保養耗材',   NULL, TRUE, 50)
ON CONFLICT (code) DO NOTHING;

-- 5.3) nx00_brand (examples; adjust to your real list)
INSERT INTO nx00_brand (code, name, name_en, is_active)
VALUES
('VDO',   'VDO',   'VDO',   TRUE),
('BOSCH', '博世',  'BOSCH', TRUE),
('HELLA', '海拉',  'HELLA', TRUE)
ON CONFLICT (code) DO NOTHING;
